export const CATALOG_REPOSITORY = Symbol('CATALOG_REPOSITORY');
export const DOCUMENT_REPOSITORY = Symbol('DOCUMENT_REPOSITORY');
export const JOB_REPOSITORY = Symbol('JOB_REPOSITORY');

export const EXTRACTION_ENGINE = Symbol('EXTRACTION_ENGINE');
export const DOCUMENT_STORAGE = Symbol('DOCUMENT_STORAGE');
export const DOCUMENT_JOB_DISPATCHER = Symbol('DOCUMENT_JOB_DISPATCHER');

export const DEFAULT_STORAGE_DIR = 'storage';
export const DEFAULT_MAX_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024;
